# Default application configuration that all configurations inherit from.

linters:
  StringQuotes:
    enabled: true
    style: double_quotes

  EmptyLineBetweenBlocks:
    enabled: false

  NestingDepth:
    enabled: false

  SelectorDepth:
    enabled: false

  SpaceBeforeBrace:
    enabled: true
    style: space
    allow_single_line_padding: true
